<script setup>
import { onMounted, ref } from 'vue'
import { eventErrorMessage, eventService } from './eventService'
import './event.css'

const reports = ref({ data: [], current_page: 1, last_page: 1 }), report = ref(null), options = ref({ courses: [], sections: [], year_levels: [] })
const loading = ref(true), detailLoading = ref(false), exporting = ref(false), error = ref('')
const listFilters = ref({ search: '', status: '', audience: '', from: '', to: '', page: 1 })
const rowFilters = ref({ search: '', status: '', course_id: '', year_level: '', section_id: '', sort: 'student', page: 1 })
const fmt = (value) => value ? new Intl.DateTimeFormat(undefined, { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)) : '—'
const percentage = (value) => `${Number(value || 0).toFixed(1)}%`
const query = (filters) => Object.fromEntries(Object.entries(filters).filter(([, value]) => value !== '' && value !== null))

async function load() { loading.value = true; error.value = ''; try { reports.value = await eventService.reports(query(listFilters.value)); options.value = await eventService.options() } catch (e) { error.value = eventErrorMessage(e) } finally { loading.value = false } }
async function open(item) { detailLoading.value = true; error.value = ''; report.value = { event: item, loading: true }; try { report.value = await eventService.report(item.id, query(rowFilters.value)) } catch (e) { report.value = null; error.value = eventErrorMessage(e) } finally { detailLoading.value = false } }
async function applyRows() { if (report.value?.event?.id) { rowFilters.value.page = 1; await open(report.value.event) } }
async function download() { if (!report.value?.event?.id || exporting.value) return; exporting.value = true; error.value = ''; try { const response = await eventService.exportReport(report.value.event.id, query(rowFilters.value)); const disposition = response.headers['content-disposition'] || ''; const filename = disposition.match(/filename="?([^";]+)"?/)?.[1] || 'event-attendance.csv'; const url = URL.createObjectURL(response.data); const anchor = document.createElement('a'); anchor.href = url; anchor.download = filename; anchor.click(); URL.revokeObjectURL(url) } catch (e) { error.value = eventErrorMessage(e) } finally { exporting.value = false } }
async function pageList(page) { listFilters.value.page = page; await load() }
async function pageRows(page) { rowFilters.value.page = page; await open(report.value.event) }
onMounted(load)
</script>

<template>
  <main class="event-page report-page">
    <header class="event-hero"><div><p class="event-eyebrow">Registrar records</p><h1>Event Reports</h1><p>Review authoritative Event attendance and export filtered records.</p></div></header>
    <p v-if="error" class="event-alert error" role="alert">{{ error }}</p>
    <form class="event-toolbar" aria-label="Report filters" @submit.prevent="load"><label><span>Search Event</span><input v-model.trim="listFilters.search" type="search" /></label><label><span>Status</span><select v-model="listFilters.status"><option value="">All statuses</option><option v-for="item in ['draft','published','cancelled','archived']" :key="item">{{ item }}</option></select></label><label><span>Audience</span><select v-model="listFilters.audience"><option value="">All audiences</option><option v-for="item in ['all_students','all_professors','all_users','course','year_level','section']" :key="item" :value="item">{{ item.replaceAll('_', ' ') }}</option></select></label><label><span>From</span><input v-model="listFilters.from" type="date" /></label><label><span>To</span><input v-model="listFilters.to" type="date" /></label><button class="event-button primary" type="submit">Apply</button></form>
    <div v-if="loading" class="event-state" aria-live="polite">Loading Event reports…</div><div v-else-if="!reports.data.length" class="event-state"><strong>No Event reports found.</strong><span>Adjust the report filters and try again.</span></div>
    <section v-else class="event-table-wrap"><table><thead><tr><th>Event</th><th>Date</th><th>Audience</th><th>Eligible</th><th>Present</th><th>Late</th><th>Attendance Rate</th><th></th></tr></thead><tbody><tr v-for="item in reports.data" :key="item.id"><td><strong>{{ item.title }}</strong><small v-if="item.parent_event_id">Sub-event</small></td><td>{{ fmt(item.starts_at) }}</td><td>{{ item.audience }}</td><td>{{ item.summary.eligible }}</td><td>{{ item.summary.present }}</td><td>{{ item.summary.late }}</td><td>{{ percentage(item.summary.attendance_rate) }}</td><td><button type="button" @click="open(item)">View Report</button></td></tr></tbody></table></section>
    <nav v-if="reports.last_page > 1" class="report-pagination" aria-label="Report pages"><button :disabled="reports.current_page <= 1" @click="pageList(reports.current_page - 1)">Previous</button><span>Page {{ reports.current_page }} of {{ reports.last_page }}</span><button :disabled="reports.current_page >= reports.last_page" @click="pageList(reports.current_page + 1)">Next</button></nav>
    <div v-if="report" class="event-modal-backdrop" @click.self="report = null"><section class="event-modal report-modal" role="dialog" aria-modal="true" aria-labelledby="report-title" tabindex="-1" @keydown.esc="report = null"><header><div><p class="event-eyebrow">Event Attendance Report</p><h2 id="report-title">{{ report.event.title }}</h2></div><button type="button" aria-label="Close report" @click="report = null">×</button></header><div v-if="detailLoading" class="event-state">Loading attendance report…</div><template v-else>
      <section class="report-information"><div><span>Schedule</span><strong>{{ fmt(report.event.starts_at) }} – {{ fmt(report.event.ends_at) }}</strong></div><div><span>Venue</span><strong>{{ report.event.venue }}</strong></div><div><span>Audience</span><strong>{{ report.event.audience }}</strong></div></section>
      <section class="report-summary" aria-label="Attendance summary"><div v-for="(value, key) in report.summary" :key="key"><strong>{{ key === 'attendance_rate' ? percentage(value) : value }}</strong><span>{{ key.replaceAll('_', ' ') }}</span></div></section>
      <form class="report-row-filters" @submit.prevent="applyRows"><input v-model.trim="rowFilters.search" type="search" placeholder="Student name or number" aria-label="Search Students" /><select v-model="rowFilters.status" aria-label="Status"><option value="">All statuses</option><option v-for="item in ['present','late','excused','absent','not_recorded']" :key="item" :value="item">{{ item.replace('_', ' ') }}</option></select><select v-model="rowFilters.course_id" aria-label="Course"><option value="">All courses</option><option v-for="course in options.courses" :key="course.id" :value="course.id">{{ course.course_code }}</option></select><select v-model="rowFilters.year_level" aria-label="Year"><option value="">All years</option><option v-for="year in options.year_levels" :key="year" :value="year">Year {{ year }}</option></select><select v-model="rowFilters.section_id" aria-label="Section"><option value="">All sections</option><option v-for="section in options.sections" :key="section.id" :value="section.id">{{ section.section_name }}</option></select><select v-model="rowFilters.sort" aria-label="Sort"><option value="student">Student</option><option value="check_in">Check-in</option><option value="status">Status</option></select><button class="event-button secondary">Apply</button><button v-if="report.capabilities?.can_export" class="event-button primary" type="button" :disabled="exporting" @click="download">{{ exporting ? 'Preparing…' : 'Export CSV' }}</button></form>
      <div v-if="!report.students.data.length" class="event-state compact"><strong>No attendance records found.</strong><span>Adjust the attendance filters and try again.</span></div><section v-else class="event-table-wrap report-attendance"><table><thead><tr><th>Student Number</th><th>Student Name</th><th>Course</th><th>Year</th><th>Section</th><th>Check-in</th><th>Status</th><th>Source</th><th>Recorded / Corrected By</th></tr></thead><tbody><tr v-for="student in report.students.data" :key="student.student_number"><td>{{ student.student_number }}</td><td><strong>{{ student.name }}</strong></td><td>{{ student.course }}</td><td>{{ student.year_level }}</td><td>{{ student.section }}</td><td>{{ fmt(student.checked_in_at) }}</td><td><span class="event-badge" :data-status="student.status">{{ student.status.replace('_', ' ') }}</span></td><td>{{ student.source }}</td><td>{{ student.recorded_by }}</td></tr></tbody></table></section>
      <nav v-if="report.students.last_page > 1" class="report-pagination"><button :disabled="report.students.current_page <= 1" @click="pageRows(report.students.current_page - 1)">Previous</button><span>Page {{ report.students.current_page }} of {{ report.students.last_page }}</span><button :disabled="report.students.current_page >= report.students.last_page" @click="pageRows(report.students.current_page + 1)">Next</button></nav>
      <section class="report-breakdowns"><article v-for="(items, group) in report.breakdowns" :key="group"><h3>By {{ group }}</h3><p v-if="!items.length">No recorded attendance.</p><dl v-else><div v-for="item in items" :key="item.label"><dt>{{ item.label }}</dt><dd>{{ item.total }}</dd></div></dl></article></section>
      <section v-if="report.sub_events?.items?.length" class="subevent-report"><h3>Sub-event Summary</h3><div v-for="child in report.sub_events.items" :key="child.id"><strong>{{ child.title }}</strong><span>{{ child.summary.present + child.summary.late }} / {{ child.summary.eligible }} attended</span></div><p>Overall unique attendees: <strong>{{ report.sub_events.overall_unique_attendees }}</strong></p></section><section v-else class="event-state compact"><strong>No sub-events configured.</strong></section>
    </template></section></div>
  </main>
</template>
