<script setup>
import { computed, nextTick, onMounted, ref, watch } from 'vue'
import { useAuthStore } from '../../stores/authStore'
import { eventErrorMessage, eventService } from './eventService'
import './event.css'

const auth = useAuthStore()
const isStaff = computed(() => ['Admin', 'Registrar Staff'].includes(auth.currentRole))
const events = ref([]), loading = ref(true), saving = ref(false), error = ref(''), notice = ref('')
const search = ref(''), status = ref(''), audience = ref(''), eventDate = ref(''), view = ref('list'), modal = ref(''), selected = ref(null)
const calendarCursor = ref(new Date(new Date().getFullYear(), new Date().getMonth(), 1))
const dialogRef = ref(null)
let dialogTrigger = null
const options = ref({ courses: [], sections: [], year_levels: [1, 2, 3, 4] })
const blank = () => ({ title: '', description: '', venue: '', starts_at: '', ends_at: '', audience_type: 'all_students', course_id: '', year_level: '', section_id: '', version: 1 })
const form = ref(blank())
const dateKey = (value) => { const date = new Date(value); return [date.getFullYear(), String(date.getMonth() + 1).padStart(2, '0'), String(date.getDate()).padStart(2, '0')].join('-') }
const filteredEvents = computed(() => events.value.filter((event) => {
  const needle = search.value.trim().toLowerCase()
  const audienceMatch = !audience.value || event.audiences.some((item) => item.audience_type === audience.value)
  const dateMatch = !eventDate.value || dateKey(event.starts_at) === eventDate.value
  return (!needle || `${event.title} ${event.venue}`.toLowerCase().includes(needle)) && (!status.value || event.status === status.value || event.managed_status === status.value) && audienceMatch && dateMatch
}))
const groups = computed(() => { const now = Date.now(); return {
  Today: filteredEvents.value.filter((e) => new Date(e.starts_at).toDateString() === new Date().toDateString()),
  Upcoming: filteredEvents.value.filter((e) => new Date(e.starts_at).getTime() > now && new Date(e.starts_at).toDateString() !== new Date().toDateString()),
  Past: filteredEvents.value.filter((e) => new Date(e.ends_at).getTime() <= now),
} })
const calendarEvents = computed(() => filteredEvents.value.filter((event) => { const date = new Date(event.starts_at); return date.getMonth() === calendarCursor.value.getMonth() && date.getFullYear() === calendarCursor.value.getFullYear() }))
const calendarGroups = computed(() => calendarEvents.value.reduce((days, event) => { const key = new Date(event.starts_at).toLocaleDateString(undefined, { month: 'short', day: 'numeric', year: 'numeric' }); (days[key] ||= []).push(event); return days }, {}))
const calendarLabel = computed(() => calendarCursor.value.toLocaleDateString(undefined, { month: 'long', year: 'numeric' }))
const shiftMonth = (amount) => { calendarCursor.value = new Date(calendarCursor.value.getFullYear(), calendarCursor.value.getMonth() + amount, 1) }
const isToday = (day) => new Date(day).toDateString() === new Date().toDateString()
const fmt = (value, dateOnly = false) => new Intl.DateTimeFormat(undefined, dateOnly ? { dateStyle: 'medium' } : { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value))
const localValue = (value) => value ? new Date(new Date(value).getTime() - new Date(value).getTimezoneOffset() * 60000).toISOString().slice(0, 16) : ''

async function load() { loading.value = true; error.value = ''; try { const page = await eventService.list({ per_page: 100 }); events.value = page.data || []; if (isStaff.value) options.value = await eventService.options() } catch (e) { error.value = eventErrorMessage(e) } finally { loading.value = false } }
function openCreate() { form.value = blank(); modal.value = 'form' }
function openEdit(event) { const audience = event.audiences[0] || {}; form.value = { ...event, starts_at: localValue(event.starts_at), ends_at: localValue(event.ends_at), audience_type: audience.audience_type || 'all_students', course_id: audience.course_id || '', year_level: audience.year_level || '', section_id: audience.section_id || '' }; modal.value = 'form' }
async function inspect(event) { error.value = ''; try { selected.value = await eventService.show(event.id); modal.value = 'detail' } catch (e) { error.value = eventErrorMessage(e) } }
function payload(intent = 'draft') { const audience = { audience_type: form.value.audience_type }; if (form.value.audience_type === 'course') audience.course_id = Number(form.value.course_id); if (form.value.audience_type === 'year_level') audience.year_level = Number(form.value.year_level); if (form.value.audience_type === 'section') audience.section_id = Number(form.value.section_id); return { title: form.value.title, description: form.value.description || null, venue: form.value.venue, starts_at: form.value.starts_at, ends_at: form.value.ends_at, audiences: [audience], intent, version: form.value.version } }
async function save(intent) { if (saving.value) return; saving.value = true; error.value = ''; try { form.value.id ? await eventService.update(form.value.id, payload(intent)) : await eventService.create(payload(intent)); modal.value = ''; notice.value = intent === 'publish' ? 'Event published.' : 'Event saved.'; await load() } catch (e) { error.value = eventErrorMessage(e) } finally { saving.value = false } }
async function changeStatus(action) { if (saving.value || !selected.value) return; saving.value = true; error.value = ''; try { await eventService.transition(selected.value.id, action, selected.value.version); modal.value = ''; notice.value = `Event ${action === 'cancel' ? 'cancelled' : `${action}ed`}.`; await load() } catch (e) { error.value = eventErrorMessage(e) } finally { saving.value = false } }
watch(modal, async (value, previous) => { if (value && !previous) { dialogTrigger = document.activeElement; await nextTick(); dialogRef.value?.focus() } else if (!value && previous) { dialogTrigger?.focus?.({ preventScroll: true }) } })
onMounted(load)
</script>

<template>
  <main class="event-page">
    <header class="event-hero"><div><p class="event-eyebrow">Campus engagement</p><h1>Event Attendance</h1><p>{{ isStaff ? 'Plan and publish campus events for verified academic audiences.' : 'Events selected for your current academic profile.' }}</p></div><button v-if="isStaff" class="event-button primary" type="button" @click="openCreate">Create Event</button></header>
    <p v-if="notice" class="event-alert success" role="status">{{ notice }}</p><p v-if="error" class="event-alert error" role="alert">{{ error }}</p>
    <section class="event-toolbar" aria-label="Event filters"><label><span>Search</span><input v-model="search" type="search" placeholder="Title or venue" /></label><label><span>Status</span><select v-model="status"><option value="">All statuses</option><option v-for="item in ['draft','published','ongoing','completed','cancelled','archived']" :key="item" :value="item">{{ item }}</option></select></label><label><span>Audience</span><select v-model="audience"><option value="">All audiences</option><option value="all_students">All Students</option><option value="all_professors">All Professors</option><option value="all_users">All academic users</option><option value="course">Course</option><option value="year_level">Year level</option><option value="section">Section</option></select></label><label><span>Date</span><input v-model="eventDate" type="date" /></label><div class="view-switch"><button type="button" :class="{ active: view === 'list' }" @click="view = 'list'">List</button><button type="button" :class="{ active: view === 'calendar' }" @click="view = 'calendar'">Calendar</button></div></section>
    <div v-if="loading" class="event-state" aria-live="polite">Loading events…</div>
    <div v-else-if="!filteredEvents.length" class="event-state"><strong>No events found</strong><span>{{ isStaff ? 'Create an event or adjust the filters.' : 'There are no events for your current audience.' }}</span></div>
    <section v-else-if="view === 'calendar'" class="event-calendar" aria-label="Event calendar"><header><button type="button" aria-label="Previous month" @click="shiftMonth(-1)">‹</button><h2>{{ calendarLabel }}</h2><button type="button" aria-label="Next month" @click="shiftMonth(1)">›</button></header><p v-if="!calendarEvents.length" class="event-calendar-empty">No events in this month.</p><article v-for="(items, day) in calendarGroups" :key="day" :class="{ 'is-today': isToday(day) }"><h2>{{ day }} <small v-if="isToday(day)">Today</small></h2><button v-for="event in items" :key="event.id" type="button" @click="inspect(event)"><strong>{{ event.title }}</strong><span>{{ fmt(event.starts_at) }} · {{ event.venue }}</span></button></article></section>
    <section v-else-if="isStaff" class="event-table-wrap"><table><thead><tr><th>Event</th><th>Schedule</th><th>Venue</th><th>Audience</th><th>Status</th><th><span class="sr-only">Actions</span></th></tr></thead><tbody><tr v-for="event in filteredEvents" :key="event.id"><td><strong>{{ event.title }}</strong></td><td>{{ fmt(event.starts_at) }}</td><td>{{ event.venue }}</td><td>{{ event.audiences.map((a) => a.label).join(', ') }}</td><td><span class="event-badge" :data-status="event.status">{{ event.status }}</span></td><td class="row-actions"><button type="button" @click="inspect(event)">View</button><button v-if="!['cancelled','archived'].includes(event.managed_status)" type="button" @click="openEdit(event)">Edit</button></td></tr></tbody></table></section>
    <section v-else class="event-groups"><template v-for="(items, group) in groups" :key="group"><div v-if="items.length"><h2>{{ group }}</h2><div class="event-cards"><button v-for="event in items" :key="event.id" class="event-card" type="button" @click="inspect(event)"><span class="event-date">{{ fmt(event.starts_at, true) }}</span><strong>{{ event.title }}</strong><span>{{ fmt(event.starts_at) }}</span><span>{{ event.venue }}</span><span class="event-badge" :data-status="event.status">{{ event.status }}</span></button></div></div></template></section>
    <div v-if="modal" class="event-modal-backdrop" @click.self="modal = ''"><section ref="dialogRef" class="event-modal" role="dialog" aria-modal="true" :aria-labelledby="modal === 'form' ? 'event-form-title' : 'event-detail-title'" tabindex="-1" @keydown.esc="modal = ''"><header><h2 :id="modal === 'form' ? 'event-form-title' : 'event-detail-title'">{{ modal === 'form' ? (form.id ? 'Edit Event' : 'Create Event') : selected?.title }}</h2><button type="button" aria-label="Close dialog" @click="modal = ''">×</button></header>
      <form v-if="modal === 'form'" class="event-form" @submit.prevent="save('draft')"><label class="wide"><span>Title</span><input v-model.trim="form.title" required maxlength="180" /></label><label class="wide"><span>Description</span><textarea v-model.trim="form.description" rows="4" maxlength="10000"></textarea></label><label><span>Starts</span><input v-model="form.starts_at" type="datetime-local" required /></label><label><span>Ends</span><input v-model="form.ends_at" type="datetime-local" required /></label><label class="wide"><span>Venue</span><input v-model.trim="form.venue" required maxlength="180" /></label><label class="wide"><span>Audience</span><select v-model="form.audience_type"><option value="all_students">All Students</option><option value="all_professors">All Professors</option><option value="all_users">All Students and Professors</option><option value="course">Course</option><option value="year_level">Year Level</option><option value="section">Section</option></select></label>
        <label v-if="form.audience_type === 'course'" class="wide"><span>Course</span><select v-model="form.course_id" required><option disabled value="">Select course</option><option v-for="course in options.courses" :key="course.id" :value="course.id">{{ course.course_code }} — {{ course.course_name }}</option></select></label><label v-if="form.audience_type === 'year_level'" class="wide"><span>Year level</span><select v-model="form.year_level" required><option disabled value="">Select year</option><option v-for="year in options.year_levels" :key="year" :value="year">Year {{ year }}</option></select></label><label v-if="form.audience_type === 'section'" class="wide"><span>Section</span><select v-model="form.section_id" required><option disabled value="">Select section</option><option v-for="section in options.sections" :key="section.id" :value="section.id">{{ section.course?.course_code }} · {{ section.section_name }}</option></select></label>
        <footer><button class="event-button secondary" type="button" @click="modal = ''">Cancel</button><button class="event-button secondary" type="submit" :disabled="saving">{{ form.id ? 'Save Changes' : 'Save Draft' }}</button><button v-if="!form.id" class="event-button primary" type="button" :disabled="saving" @click="save('publish')">Publish</button></footer></form>
      <div v-else-if="selected" class="event-detail"><span class="event-badge" :data-status="selected.status">{{ selected.status }}</span><p>{{ selected.description || 'No description provided.' }}</p><dl><div><dt>Schedule</dt><dd>{{ fmt(selected.starts_at) }} – {{ fmt(selected.ends_at) }}</dd></div><div><dt>Venue</dt><dd>{{ selected.venue }}</dd></div><div><dt>Audience</dt><dd>{{ selected.audiences.map((a) => a.label).join(', ') }}</dd></div></dl><section v-if="isStaff && selected.audit?.length" class="event-audit"><h3>Activity</h3><ol><li v-for="entry in selected.audit" :key="`${entry.action}-${entry.created_at}`"><strong>{{ entry.action.replace('event.', '') }}</strong><span>{{ entry.actor_role }} · {{ fmt(entry.created_at) }}</span></li></ol></section><footer v-if="isStaff"><button v-if="!['cancelled','archived'].includes(selected.managed_status)" class="event-button secondary" type="button" @click="openEdit(selected)">Edit</button><button v-if="selected.managed_status === 'draft'" class="event-button primary" type="button" :disabled="saving" @click="changeStatus('publish')">Publish</button><button v-if="['draft','published'].includes(selected.managed_status)" class="event-button danger" type="button" :disabled="saving" @click="changeStatus('cancel')">Cancel Event</button><button v-if="selected.managed_status !== 'archived'" class="event-button secondary" type="button" :disabled="saving" @click="changeStatus('archive')">Archive</button></footer></div>
    </section></div>
  </main>
</template>
