import { apiClient } from '../../services/apiClient'

const data = (response) => response.data.data
export const gradingValidationErrors = (error) => error.response?.data?.errors || {}
export const gradingError = (error) => Object.values(gradingValidationErrors(error)).flat().find(Boolean) || error.response?.data?.message || 'Unable to complete the grading request.'
export const gradingService = {
  students: (params = {}) => apiClient.get('/students', { params }).then((response) => response.data),
  studentOptions: () => apiClient.get('/students/bulk-options').then(data),
  periods: (params = {}) => apiClient.get('/grading/periods', { params }).then(data),
  createPeriod: (payload) => apiClient.post('/grading/periods', payload).then(data),
  updatePeriod: (id, payload) => apiClient.put(`/grading/periods/${id}`, payload).then(data),
  archivePeriod: (id, version) => apiClient.patch(`/grading/periods/${id}/archive`, { version }).then(data),
  classes: (params = {}) => apiClient.get('/grading/classes', { params }).then(data),
  workspace: (id) => apiClient.post(`/grading/classes/${id}/workspace`).then(data),
  addAssessment: (sheet, payload) => apiClient.post(`/grading/sheets/${sheet}/assessments`, payload).then(data),
  updateAssessment: (sheet, id, payload) => apiClient.put(`/grading/sheets/${sheet}/assessments/${id}`, payload).then(data),
  assessmentStatus: (sheet, id, payload) => apiClient.patch(`/grading/sheets/${sheet}/assessments/${id}/status`, payload).then(data),
  saveScores: (sheet, payload) => apiClient.put(`/grading/sheets/${sheet}/scores`, payload).then(data),
  saveWeights: (sheet, period, weights) => apiClient.put(`/grading/sheets/${sheet}/weights/${period}`, { weights }).then(data),
  readiness: (sheet) => apiClient.get(`/grading/sheets/${sheet}/readiness`).then(data),
  saveFinalWeights: (sheet, payload) => apiClient.put(`/grading/sheets/${sheet}/final-weights`, payload).then(data),
  submit: (sheet, version) => apiClient.post(`/grading/sheets/${sheet}/submit`, { version }).then(data),
  reviews: (params = {}) => apiClient.get('/grading/reviews', { params }).then(data),
  review: (sheet) => apiClient.get(`/grading/reviews/${sheet}`).then(data),
  approve: (sheet, version) => apiClient.post(`/grading/reviews/${sheet}/approve`, { version }).then(data),
  returnSheet: (sheet, version, reason) => apiClient.post(`/grading/reviews/${sheet}/return`, { version, reason }).then(data),
  releases: () => apiClient.get('/grading/releases').then(data),
  createRelease: (payload) => apiClient.post('/grading/releases', payload).then(data),
  updateRelease: (id, payload) => apiClient.put(`/grading/releases/${id}`, payload).then(data),
  executeRelease: (id) => apiClient.post(`/grading/releases/${id}/execute`).then(data),
  studentGrades: (params = {}) => apiClient.get('/grading/student/grades', { params }).then(data),
  studentExport: (params = {}) => apiClient.get('/grading/student/grades/export', { params, responseType: 'blob' }),
  createConversation: (sheet) => apiClient.post(`/grading/student/grades/${sheet}/conversation`).then(data),
  professorConversations: () => apiClient.get('/grading/professor/conversations').then(data),
  conversation: (id) => apiClient.get(`/grading/conversations/${id}`).then(data),
  sendMessage: (id, payload) => apiClient.post(`/grading/conversations/${id}/messages`, payload).then(data),
  unsendMessage: (id) => apiClient.delete(`/grading/messages/${id}`).then(data),
  messageAttachment: (id) => apiClient.get(`/grading/messages/${id}/attachment`, { responseType: 'blob' }),
  staffStudentGrades: (student, params = {}) => apiClient.get(`/grading/staff/students/${student}`, { params }).then(data),
  staffStudentExport: (student, params = {}) => apiClient.get(`/grading/staff/students/${student}/export`, { params, responseType: 'blob' }),
  classExport: (sheet) => apiClient.get(`/grading/staff/sheets/${sheet}/export`, { responseType: 'blob' }),
}
