<script setup>
import { onBeforeUnmount, ref, watch } from 'vue'
import { gradingError, gradingService } from './gradingService'

const props = defineProps({ conversationId: { type: Number, required: true } })
const emit = defineEmits(['changed'])
const conversation = ref(null), loading = ref(true), sending = ref(false), error = ref(''), body = ref(''), attachment = ref(null), previews = ref({})
const releasePreviews = () => { Object.values(previews.value).forEach(URL.revokeObjectURL); previews.value = {} }
async function load(){loading.value=true;error.value='';releasePreviews();try{conversation.value=await gradingService.conversation(props.conversationId);await Promise.all((conversation.value.messages||[]).filter(m=>m.attachment_url).map(async m=>{try{const response=await gradingService.messageAttachment(m.id);previews.value={...previews.value,[m.id]:URL.createObjectURL(response.data)}}catch{}}));emit('changed')}catch(e){error.value=gradingError(e)}finally{loading.value=false}}
function choose(event){attachment.value=event.target.files?.[0]||null}
async function send(){if(sending.value||(!body.value.trim()&&!attachment.value))return;sending.value=true;error.value='';try{const form=new FormData();if(body.value.trim())form.append('body',body.value.trim());if(attachment.value)form.append('attachment',attachment.value);await gradingService.sendMessage(props.conversationId,form);body.value='';attachment.value=null;await load()}catch(e){error.value=gradingError(e)}finally{sending.value=false}}
async function unsend(message){if(sending.value)return;sending.value=true;error.value='';try{await gradingService.unsendMessage(message.id);await load()}catch(e){error.value=gradingError(e)}finally{sending.value=false}}
watch(()=>props.conversationId,load,{immediate:true})
onBeforeUnmount(releasePreviews)
</script>

<template><section class="grade-chat" aria-live="polite"><header v-if="conversation"><div><strong>{{conversation.grade.subject_code}} — {{conversation.grade.subject_name}}</strong><span>{{conversation.grade.section}} · {{conversation.grade.professor}}</span></div></header><p v-if="loading" class="grading-state">Loading messages…</p><p v-else-if="error" class="grading-alert error" role="alert">{{error}}</p><div v-else class="grade-chat-history"><p v-if="!conversation.messages.length" class="grade-chat-empty">No messages yet. Start a grade-related conversation.</p><article v-for="message in conversation.messages" :key="message.id" class="grade-chat-bubble" :class="{mine:message.mine,unsent:message.unsent_at}"><strong>{{message.sender}}</strong><p v-if="message.unsent_at">Message unsent</p><p v-else-if="message.body">{{message.body}}</p><img v-if="previews[message.id]" :src="previews[message.id]" :alt="message.attachment_name||'Message image attachment'"><small>{{new Date(message.created_at).toLocaleString()}}<template v-if="message.mine&&message.read_at"> · Read</template></small><button v-if="message.mine&&!message.unsent_at" type="button" :disabled="sending" @click="unsend(message)">Unsend</button></article></div><form class="grade-chat-composer" @submit.prevent="send"><label><span>Message</span><textarea v-model="body" maxlength="5000" rows="3" placeholder="Write a grade-related message"></textarea></label><label class="grade-chat-file"><span>Optional image</span><input type="file" accept="image/jpeg,image/png,image/webp,image/gif" @change="choose"><small>{{attachment?.name||'JPEG, PNG, WebP, or GIF · maximum 5 MB'}}</small></label><button class="grading-button primary" :disabled="sending||(!body.trim()&&!attachment)">{{sending?'Sending…':'Send Message'}}</button></form></section></template>
