import { registerSW } from 'virtual:pwa-register'
import { Capacitor } from '@capacitor/core'

// Registers the service worker generated by vite-plugin-pwa.
// The app shell can be installed and updated automatically after production builds.
if (!Capacitor.isNativePlatform()) {
  registerSW({
    immediate: true,
  })
}
