<script setup>
import { computed, onMounted, ref } from 'vue'
import { useAuthStore } from '../../stores/authStore'
import { ROLES } from '../../config/accessControl'
import { fetchEarlyWarnings, fetchMyRisk, fetchMyRiskNotifications, markRiskNotificationRead, sendRiskNotification } from './services/monitoringApi'
import AiHelpChatbot from './components/AiHelpChatbot.vue'
import StudyPlansPanel from './components/StudyPlansPanel.vue'
const auth = useAuthStore(); const data = ref(null); const selectedId = ref(null); const error = ref(''); const loading = ref(true); const notice = ref('')
const isStudent = computed(() => auth.currentRole === ROLES.STUDENT)
const students = computed(() => data.value?.students || [])
const selected = computed(() => students.value.find((student) => student.student_id === selectedId.value) || students.value[0] || null)
const load = async () => { loading.value = true; error.value = ''; try { data.value = await (isStudent.value ? fetchMyRisk() : fetchEarlyWarnings()); selectedId.value = students.value[0]?.student_id || null } catch (err) { error.value = err.response?.data?.message || 'Unable to load academic monitoring.' } finally { loading.value = false } }
const notify = async () => { if (!selected.value) return; try { await sendRiskNotification(selected.value.student_id); notice.value = 'Risk notification sent.' } catch (err) { notice.value = err.response?.data?.message || 'Unable to send the notification.' } }
const readNotifications = async () => { try { const payload = await fetchMyRiskNotifications(); await Promise.all((payload.notifications || []).filter((n) => !n.is_read).map((n) => markRiskNotificationRead(n.id))); notice.value = payload.unread ? 'Risk notifications marked as read.' : 'No unread risk notifications.' } catch (err) { notice.value = err.response?.data?.message || 'Unable to load notifications.' } }
onMounted(load)
</script>
<template><main class="monitoring-page"><header class="page-head"><div><p class="eyebrow">Academic Monitoring</p><h1>Early Warnings</h1><p>Approved grades and assigned-subject access only.</p></div><div><button type="button" @click="load">Refresh</button><button v-if="isStudent" type="button" @click="readNotifications">Notifications</button></div></header><p v-if="error" class="message error" role="alert">{{ error }}</p><p v-if="notice" class="message">{{ notice }}</p><p v-if="loading">Loading academic assessment...</p><template v-else><section class="summary"><article><span>High risk</span><strong>{{ data?.summary?.high || 0 }}</strong></article><article><span>Moderate risk</span><strong>{{ data?.summary?.moderate || 0 }}</strong></article><article><span>Stable</span><strong>{{ data?.summary?.low || 0 }}</strong></article></section><div class="workspace"><aside v-if="!isStudent" class="student-list"><button v-for="student in students" :key="student.student_id" type="button" :class="{ active: selected?.student_id === student.student_id }" @click="selectedId = student.student_id"><strong>{{ student.student_number }}</strong><span>{{ student.risk_label }}</span></button></aside><section v-if="selected" class="assessment"><header><div><h2>{{ isStudent ? 'My assessment' : selected.student_number }}</h2><p>{{ selected.headline }}</p></div><button v-if="!isStudent" type="button" @click="notify">Notify student</button></header><ul><li v-for="subject in selected.subjects" :key="subject.subject_code"><strong>{{ subject.subject_code }} · {{ subject.subject_name }}</strong><span>{{ subject.average_grade }} · {{ subject.risk_level }}</span></li></ul><AiHelpChatbot :student-id="selected.student_id" /><StudyPlansPanel :student-id="selected.student_id" /></section><p v-else>No approved grade records are available.</p></div></template></main></template>
<style scoped>.monitoring-page{max-width:1200px;margin:0 auto;padding:24px}.page-head,.page-head>div:last-child,.assessment header{display:flex;align-items:start;justify-content:space-between;gap:12px}.eyebrow{color:#106a2e;font-weight:700;margin:0}h1,h2{margin:4px 0}button{border:1px solid #106a2e;background:#fff;color:#106a2e;border-radius:5px;padding:8px 11px;font-weight:700}.summary{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin:20px 0}.summary article,.student-list,.assessment{background:#fff;border:1px solid #d7dfd6;border-radius:8px;padding:16px}.summary strong{display:block;font-size:1.5rem}.workspace{display:grid;grid-template-columns:250px minmax(0,1fr);gap:16px}.student-list{display:grid;align-content:start;gap:7px}.student-list button{text-align:left}.student-list button.active{background:#e6f2e8}.assessment{display:grid;gap:18px}.assessment ul{list-style:none;padding:0;margin:0}.assessment li{display:flex;justify-content:space-between;padding:10px 0;border-top:1px solid #e5e9e5}.message{padding:10px;background:#edf5ee}.error{background:#fff0ef;color:#a8291f}@media(max-width:760px){.workspace{grid-template-columns:1fr}.summary{grid-template-columns:1fr}.page-head{display:grid}.assessment li{display:grid;gap:4px}}</style>
