<?php

namespace App\Services\Event;

use App\Models\Event;
use App\Models\EventAttendance;
use App\Models\Student;
use App\Models\User;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Pagination\LengthAwarePaginator;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use Symfony\Component\HttpFoundation\StreamedResponse;

class EventReportService
{
    public function __construct(private readonly EventAudienceResolver $audiences, private readonly EventAuditWriter $audit) {}

    public function index(array $filters, User $user): LengthAwarePaginator
    {
        $query = $this->audiences->visibleTo(Event::query(), $user)
            ->with(['audiences.course:id,course_code', 'audiences.section:id,section_name', 'parent.audiences.course:id,course_code', 'parent.audiences.section:id,section_name']);
        $query->when($filters['search'] ?? null, fn (Builder $q, $value) => $q->where(fn (Builder $event) => $event->where('title', 'like', "%$value%")->orWhere('venue', 'like', "%$value%")))
            ->when($filters['status'] ?? null, fn (Builder $q, $value) => $q->where('status', $value))
            ->when($filters['from'] ?? null, fn (Builder $q, $value) => $q->whereDate('ends_at', '>=', $value))
            ->when($filters['to'] ?? null, fn (Builder $q, $value) => $q->whereDate('starts_at', '<=', $value))
            ->when($filters['audience'] ?? null, function (Builder $q, $value): void {
                $q->where(fn (Builder $event) => $event->whereHas('audiences', fn (Builder $audience) => $audience->where('audience_type', $value))
                    ->orWhere(fn (Builder $inherited) => $inherited->whereDoesntHave('audiences')->whereHas('parent.audiences', fn (Builder $audience) => $audience->where('audience_type', $value))));
            });
        $page = $query->orderByDesc('starts_at')->paginate($filters['per_page'] ?? 25);
        $page->getCollection()->transform(fn (Event $event) => $this->eventSummary($event));

        return $page;
    }

    public function report(Event $event, array $filters, User $actor, bool $audit = true): array
    {
        $event->loadMissing(['audiences.course:id,course_code', 'audiences.section:id,section_name', 'parent.audiences.course:id,course_code', 'parent.audiences.section:id,section_name']);
        $students = $this->studentQuery($event, $filters);
        $page = $students->paginate($filters['per_page'] ?? 50);
        $ids = $page->getCollection()->pluck('id');
        $attendance = EventAttendance::query()->where('event_id', $event->id)->whereIn('student_id', $ids)
            ->with(['courseAtAttendance:id,course_code', 'sectionAtAttendance:id,section_name,year_level', 'recorder.profile'])->get()->keyBy('student_id');
        $page->getCollection()->transform(fn (Student $student) => $this->row($student, $attendance->get($student->id)));
        if ($audit) {
            DB::transaction(fn () => $this->audit->write($event, $actor, 'report.generated', ['filters' => $this->safeFilters($filters)]));
        }

        return [
            'event' => $this->eventInformation($event),
            'summary' => $this->summary($event),
            'breakdowns' => $this->breakdowns($event),
            'sub_events' => $this->subEventSummary($event),
            'students' => $page,
        ];
    }

    public function csv(Event $event, array $filters, User $actor): StreamedResponse
    {
        DB::transaction(fn () => $this->audit->write($event, $actor, 'report.exported', ['format' => 'csv', 'filters' => $this->safeFilters($filters)]));
        $filename = Str::slug($event->title).'-attendance-'.$event->starts_at->format('Y-m-d').'.csv';
        $summary = $this->summary($event);
        $information = $this->eventInformation($event);

        return response()->streamDownload(function () use ($event, $filters, $actor, $summary, $information): void {
            $out = fopen('php://output', 'w');
            fputcsv($out, ['Colegio de Montalban']);
            fputcsv($out, ['Event Attendance Report']);
            fputcsv($out, ['Event', $information['title']]);
            fputcsv($out, ['Schedule', $information['starts_at'].' - '.$information['ends_at']]);
            fputcsv($out, ['Venue', $information['venue']]);
            fputcsv($out, ['Audience', $information['audience']]);
            fputcsv($out, ['Generated at', now()->toIso8601String()]);
            fputcsv($out, ['Generated by', trim(($actor->profile?->first_name ?? '').' '.($actor->profile?->last_name ?? '')) ?: $actor->username]);
            fputcsv($out, []);
            fputcsv($out, ['Eligible', $summary['eligible'], 'Present', $summary['present'], 'Late', $summary['late'], 'Excused', $summary['excused'], 'Absent / Not Checked In', $summary['absent'], 'Attendance Rate', $summary['attendance_rate'].'%']);
            fputcsv($out, []);
            fputcsv($out, ['Student Number', 'Student Name', 'Course', 'Year', 'Section', 'Check-in Time', 'Status', 'Source', 'Recorded / Corrected By']);
            $query = $this->studentQuery($event, $filters);
            $query->chunkById(500, function ($students) use ($event, $out): void {
                $records = EventAttendance::query()->where('event_id', $event->id)->whereIn('student_id', $students->pluck('id'))
                    ->with(['courseAtAttendance:id,course_code', 'sectionAtAttendance:id,section_name,year_level', 'recorder.profile'])->get()->keyBy('student_id');
                foreach ($students as $student) {
                    $row = $this->row($student, $records->get($student->id));
                    fputcsv($out, [$row['student_number'], $row['name'], $row['course'], $row['year_level'], $row['section'], $row['checked_in_at'], $row['status'], $row['source'], $row['recorded_by']]);
                }
            }, 'students.id', 'id');
            fclose($out);
        }, $filename, ['Content-Type' => 'text/csv; charset=UTF-8', 'Cache-Control' => 'private, no-store']);
    }

    public function summary(Event $event): array
    {
        $eligible = $this->audiences->eligibleStudents($event)->count();
        $counts = EventAttendance::query()->where('event_id', $event->id)->selectRaw('status, count(*) aggregate')->groupBy('status')->pluck('aggregate', 'status');
        $present = (int) ($counts['present'] ?? 0);
        $late = (int) ($counts['late'] ?? 0);
        $excused = (int) ($counts['excused'] ?? 0);

        return [
            'eligible' => $eligible, 'present' => $present, 'late' => $late, 'excused' => $excused,
            'absent' => max(0, $eligible - $present - $late - $excused),
            'attendance_rate' => $eligible ? round((($present + $late) / $eligible) * 100, 1) : 0,
        ];
    }

    private function studentQuery(Event $event, array $filters): Builder
    {
        $eligible = $this->audiences->eligibleStudents($event)->select('students.id');
        $query = Student::query()->select('students.*')->join('user_profiles as report_profiles', 'report_profiles.id', '=', 'students.user_profile_id')
            ->leftJoin('event_attendances as report_attendance', fn ($join) => $join->on('report_attendance.student_id', '=', 'students.id')->where('report_attendance.event_id', $event->id))
            ->where(fn (Builder $students) => $students->whereIn('students.id', $eligible)->orWhereNotNull('report_attendance.id'))
            ->with(['userProfile', 'course:id,course_code', 'enrollments' => fn ($q) => $q->whereIn('status', ['enrolled', 'completed'])->whereHas('academicYear', fn ($year) => $year->where('status', 'active'))->whereHas('semester', fn ($semester) => $semester->where('status', 'active'))->with('section:id,section_name,year_level')]);
        $query->when($filters['search'] ?? null, fn (Builder $q, $value) => $q->where(fn (Builder $student) => $student->where('students.student_number', 'like', "%$value%")->orWhere('report_profiles.first_name', 'like', "%$value%")->orWhere('report_profiles.last_name', 'like', "%$value%")))
            ->when($filters['status'] ?? null, fn (Builder $q, $value) => $value === 'not_recorded' ? $q->whereNull('report_attendance.id') : $q->where('report_attendance.status', $value))
            ->when($filters['course_id'] ?? null, fn (Builder $q, $value) => $q->where(fn (Builder $academic) => $academic->where('report_attendance.course_id_at_attendance', $value)->orWhere(fn (Builder $current) => $current->whereNull('report_attendance.id')->where('students.course_id', $value))))
            ->when($filters['year_level'] ?? null, fn (Builder $q, $value) => $q->where(fn (Builder $academic) => $academic->where('report_attendance.year_level_at_attendance', $value)->orWhere(fn (Builder $current) => $current->whereNull('report_attendance.id')->where(fn (Builder $year) => $year->where('students.year_level', $value)->orWhereHas('enrollments.section', fn (Builder $section) => $section->where('year_level', $value))))))
            ->when($filters['section_id'] ?? null, fn (Builder $q, $value) => $q->where(fn (Builder $academic) => $academic->where('report_attendance.section_id_at_attendance', $value)->orWhere(fn (Builder $current) => $current->whereNull('report_attendance.id')->whereHas('enrollments', fn (Builder $enrollment) => $enrollment->where('section_id', $value)))))
            ->when(($filters['sort'] ?? 'student') === 'check_in', fn (Builder $q) => $q->orderByRaw('report_attendance.checked_in_at is null')->orderBy('report_attendance.checked_in_at'))
            ->when(($filters['sort'] ?? 'student') === 'status', fn (Builder $q) => $q->orderByRaw("coalesce(report_attendance.status, 'not_recorded')"))
            ->orderBy('report_profiles.last_name')->orderBy('report_profiles.first_name')->orderBy('students.id');

        return $query;
    }

    private function row(Student $student, ?EventAttendance $attendance): array
    {
        $enrollment = $student->enrollments->first();
        $hasSnapshot = $attendance && ($attendance->course_id_at_attendance || $attendance->year_level_at_attendance || $attendance->section_id_at_attendance);

        return [
            'student_number' => $student->student_number,
            'name' => trim($student->userProfile->first_name.' '.$student->userProfile->last_name),
            'course' => $attendance ? ($hasSnapshot ? ($attendance->courseAtAttendance?->course_code ?? '—') : 'Historical context unavailable') : ($student->course?->course_code ?? '—'),
            'year_level' => $attendance ? ($hasSnapshot ? ($attendance->year_level_at_attendance ?? '—') : '—') : ($enrollment?->section?->year_level ?? $student->year_level ?? '—'),
            'section' => $attendance ? ($hasSnapshot ? ($attendance->sectionAtAttendance?->section_name ?? '—') : '—') : ($enrollment?->section?->section_name ?? '—'),
            'checked_in_at' => $attendance?->checked_in_at?->toIso8601String(),
            'status' => $attendance?->status ?? 'not_recorded', 'source' => $attendance?->source ?? '—',
            'recorded_by' => $attendance ? (trim(($attendance->recorder?->profile?->first_name ?? '').' '.($attendance->recorder?->profile?->last_name ?? '')) ?: 'System') : '—',
        ];
    }

    private function eventSummary(Event $event): array
    {
        return $this->eventInformation($event) + ['summary' => $this->summary($event)];
    }

    private function eventInformation(Event $event): array
    {
        $audiences = $event->audiences->isNotEmpty() ? $event->audiences : ($event->parent?->audiences ?? collect());

        return [
            'id' => $event->id, 'parent_event_id' => $event->parent_event_id, 'title' => $event->title,
            'starts_at' => $event->starts_at->toIso8601String(), 'ends_at' => $event->ends_at->toIso8601String(),
            'venue' => $event->venue, 'status' => $event->presentationStatus(),
            'audience' => $audiences->map(fn ($a) => match ($a->audience_type) {
                'all_students' => 'All Students', 'all_professors' => 'All Professors', 'all_users' => 'All academic users',
                'course' => $a->course?->course_code ?? 'Course', 'year_level' => 'Year '.$a->year_level,
                'section' => $a->section?->section_name ?? 'Section', default => 'Audience',
            })->implode(', ').($event->audiences->isEmpty() && $event->parent ? ' (inherited)' : ''),
        ];
    }

    private function breakdowns(Event $event): array
    {
        $base = EventAttendance::query()->where('event_attendances.event_id', $event->id)->whereIn('event_attendances.status', ['present', 'late', 'excused']);
        $course = (clone $base)->leftJoin('courses', 'courses.id', '=', 'event_attendances.course_id_at_attendance')->selectRaw("coalesce(courses.course_code, 'Unavailable') label, count(*) total")->groupBy('courses.course_code')->orderBy('label')->get();
        $year = (clone $base)->selectRaw("coalesce(cast(event_attendances.year_level_at_attendance as char), 'Unavailable') label, count(*) total")->groupBy('event_attendances.year_level_at_attendance')->orderBy('event_attendances.year_level_at_attendance')->get();
        $section = (clone $base)->leftJoin('sections', 'sections.id', '=', 'event_attendances.section_id_at_attendance')->selectRaw("coalesce(sections.section_name, 'Unavailable') label, count(*) total")->groupBy('sections.section_name')->orderBy('label')->get();

        return ['course' => $course, 'year' => $year, 'section' => $section];
    }

    private function subEventSummary(Event $event): array
    {
        if ($event->parent_event_id) {
            return [];
        }
        $children = $event->subEvents()->with(['audiences', 'parent.audiences'])->get();
        $items = $children->map(fn (Event $child) => $this->eventInformation($child) + ['summary' => $this->summary($child)])->values();
        $unique = EventAttendance::query()->whereIn('event_id', $children->pluck('id'))->whereIn('status', ['present', 'late'])->distinct('student_id')->count('student_id');

        return ['items' => $items, 'overall_unique_attendees' => $unique];
    }

    private function safeFilters(array $filters): array
    {
        return collect($filters)->only(['status', 'course_id', 'year_level', 'section_id', 'search', 'sort'])->filter(fn ($value) => $value !== null && $value !== '')->all();
    }
}
