<script setup>
import { ref,onMounted,onBeforeUnmount } from 'vue'
import { apiClient } from '../../services/apiClient'
import { termLabel,safeError } from './enrollment'
import EnrollmentSchedule from './EnrollmentSchedule.vue'
const data=ref(null),roster=ref(null),selected=ref(null),error=ref(''),busy=ref(false),page=ref(1),rosterPage=ref(1);let epoch=0
async function load(){const v=++epoch;busy.value=true;error.value='';try{const r=await apiClient.get('/enrollment/academic/professor',{params:{page:page.value}});if(v===epoch)data.value=r.data.data}catch(e){if(v===epoch)error.value=safeError(e)}finally{if(v===epoch)busy.value=false}}
async function inspect(s){const v=++epoch;busy.value=true;error.value='';try{const r=await apiClient.get(`/enrollment/academic/professor/sections/${s.id}`,{params:{page:rosterPage.value}});if(v!==epoch)return;selected.value=s;roster.value=r.data.data}catch(e){if(v===epoch)error.value=safeError(e)}finally{if(v===epoch)busy.value=false}}
onMounted(load);onBeforeUnmount(()=>{epoch++})
</script>
<template><header class="page-header"><p class="page-kicker">Enrollment</p><h1 class="page-title">My Teaching Assignments</h1></header><p v-if="error" role="alert">{{ error }} <button @click="load">Reload</button></p><p v-if="busy" role="status">Loading…</p><template v-if="data"><div v-for="s in data.data" :key="s.id" class="en-card"><h2>{{ s.section_name }} · {{ termLabel(s) }}</h2><EnrollmentSchedule :schedules="s.schedules"/><button :disabled="busy" @click="rosterPage=1;inspect(s)">View enrolled Students</button></div><p v-if="!data.data.length">No assigned sections.</p><div class="en-actions"><button :disabled="busy||page<=1" @click="page--;load()">Previous</button><button :disabled="busy||page>=data.last_page" @click="page++;load()">Next</button></div></template><div v-if="roster" class="en-card"><h2>{{ selected.section_name }} roster</h2><div class="en-table"><table><thead><tr><th>Student number</th><th>Name</th></tr></thead><tbody><tr v-for="r in roster.data" :key="r.id"><td>{{ r.student.student_number }}</td><td>{{ r.student.user_profile.first_name }} {{ r.student.user_profile.last_name }}</td></tr></tbody></table></div><div class="en-actions"><button :disabled="busy||rosterPage<=1" @click="rosterPage--;inspect(selected)">Previous Students</button><button :disabled="busy||rosterPage>=roster.last_page" @click="rosterPage++;inspect(selected)">More Students</button></div></div></template>
