<script setup>
import { computed, ref, watch, onBeforeUnmount } from 'vue'
import { useAuthStore } from '../../stores/authStore'
import { apiClient } from '../../services/apiClient'
import { ROLES } from '../../config/accessControl'
import { label, termLabel, safeError } from './enrollment'
import EnrollmentDialog from './EnrollmentDialog.vue'
const props=defineProps({applicationId:{type:Number,required:true}}), emit=defineEmits(['changed'])
const auth=useAuthStore(), staff=computed(()=>[ROLES.ADMIN,ROLES.REGISTRAR_STAFF].includes(auth.currentRole))
const data=ref(null), selected=ref([]), section=ref(''), busy=ref(false), error=ref(''), notice=ref(''), confirm=ref(false), sectionPage=ref(1)
let epoch=0
const canSelect=computed(()=>data.value?.application.status==='approved' && data.value.application.classification!=='regular' && (staff.value||data.value.application.classification==='irregular'))
const units=computed(()=>data.value?.load.candidates.filter(s=>selected.value.includes(s.id)).reduce((sum,s)=>sum+Number(s.units),0)||0)
async function load(){const v=++epoch;busy.value=true;error.value='';try{const r=await apiClient.get(`/enrollment/academic/applications/${props.applicationId}`,{params:{page:sectionPage.value}});if(v!==epoch)return;data.value=r.data.data;selected.value=data.value.load.selected_subject_ids.length?data.value.load.selected_subject_ids:data.value.application.classification==='regular'?data.value.load.standard_subject_ids:[];section.value=data.value.application.section_id||''}catch(e){if(v===epoch)error.value=safeError(e)}finally{if(v===epoch)busy.value=false}}
async function act(action){if(busy.value)return;const v=++epoch;busy.value=true;error.value='';confirm.value=false;try{await apiClient.post(`/enrollment/academic/applications/${props.applicationId}/${action}`,{version:data.value.application.version,subject_ids:selected.value,section_id:Number(section.value),confirmed:true});if(v!==epoch)return;notice.value=action==='finalize'?'Academic enrollment completed. COR is available.':action==='assign'?'Section assigned.':'Subject load saved.';await load();emit('changed')}catch(e){if(v===epoch)error.value=safeError(e)}finally{if(v===epoch)busy.value=false}}
watch(()=>[props.applicationId,auth.currentUser?.id,auth.currentRole],()=>{data.value=null;load()},{immediate:true});onBeforeUnmount(()=>{epoch++})
</script>
<template><section class="en-card"><h2>Subjects and academic enrollment</h2><p v-if="error" role="alert">{{ error }} <button :disabled="busy" @click="load">Reload load</button></p><p v-if="busy" role="status">Loading…</p><p v-if="notice" role="status">{{ notice }}</p><template v-if="data"><p>{{ label(data.application.classification) }} · {{ termLabel(data.application.period) }}</p><p v-if="data.application.classification==='regular'">Your standard load comes directly from your curriculum, year level and semester.</p><p v-else>Select an active curriculum load. Recorded completed subjects and prerequisites are checked again before enrollment.</p><div class="en-table"><table><thead><tr><th>Include</th><th>Subject</th><th>Units</th><th>Eligibility</th></tr></thead><tbody><tr v-for="s in data.load.candidates" :key="s.id"><td><input type="checkbox" :aria-label="`Select ${s.subject_code}`" :value="s.id" v-model="selected" :disabled="busy||!canSelect||s.completed||!s.prerequisite_met"></td><td>{{ s.subject_code }} — {{ s.subject_name }}</td><td>{{ s.units }}</td><td>{{ s.completed?'Already completed':!s.prerequisite_met?'Prerequisite not completed':'Eligible' }}</td></tr></tbody></table></div><p v-if="!data.load.candidates.length">No active curriculum subjects are configured for this semester.</p><p><strong>Total units: {{ units }}</strong></p><p>{{ data.application.load_reviewed_at?'Staff-reviewed load':'Staff review is required before finalization.' }}</p><div class="en-actions"><button v-if="data.application.status==='approved' && (staff||canSelect)" :disabled="busy||!selected.length" @click="act('subjects')">{{ staff?'Prepare / approve subject load':'Save selected subjects' }}</button></div>
<template v-if="staff && data.application.status==='approved'"><label>Assign section<select v-model="section" :disabled="busy"><option value="">Choose section</option><option v-for="s in data.sections.data" :key="s.id" :value="s.id">{{ s.section_name }} — {{ s.enrolled_count+s.reserved_count }}/{{ s.capacity }} seats</option></select></label><div v-if="data.sections.last_page>1" class="en-actions"><button :disabled="busy||sectionPage<=1" @click="sectionPage--;load()">Previous sections</button><button :disabled="busy||sectionPage>=data.sections.last_page" @click="sectionPage++;load()">More sections</button></div><div class="en-actions"><button :disabled="busy||!section" @click="act('assign')">Assign section</button><button :disabled="busy||!data.application.section_id||!data.application.load_reviewed_at" @click="confirm=true">Finalize academic enrollment</button></div></template>
<p v-if="data.application.section">Assigned section: {{ data.application.section.section_name }}</p><p v-if="data.application.enrollment_id">Academically enrolled. <RouterLink :to="`/enrollment/cor?record=${data.application.enrollment_id}`" v-if="!staff">View COR</RouterLink></p></template>
<EnrollmentDialog v-if="confirm" labelledby="en-finalize-title" :busy="busy" @cancel="confirm=false"><h2 id="en-finalize-title">Finalize academic enrollment?</h2><p>{{ data.application.student?.user_profile?.first_name }} {{ data.application.student?.user_profile?.last_name }} · {{ data.application.student?.student_number }}</p><p>{{ units }} units · {{ data.application.section?.section_name }} · {{ termLabel(data.application.period) }}</p><p>This creates the academic enrollment and subject records after all eligibility, capacity and schedule checks pass.</p><div class="en-actions"><button @click="confirm=false">Go back</button><button @click="act('finalize')">Confirm final enrollment</button></div></EnrollmentDialog>
</section></template>
