<script setup>
import { ref,computed,watch,onBeforeUnmount } from 'vue'
import { useRoute } from 'vue-router'
import { apiClient } from '../../services/apiClient'
import { safeError,label,termLabel } from './enrollment'
import EnrollmentSchedule from './EnrollmentSchedule.vue'
import EnrollmentCor from './EnrollmentCor.vue'
import EnrollmentDialog from './EnrollmentDialog.vue'
const route=useRoute(),mode=computed(()=>route.name==='enrollment-sections'?'sections':route.name==='enrollment-scheduling'?'scheduling':'records')
const options=ref(null),data=ref(null),sections=ref(null),scheduleData=ref(null),sectionId=ref(''),sectionPage=ref(1),profPage=ref(1),page=ref(1),form=ref(null),record=ref(null),remove=ref(null),reassignment=ref(null),busy=ref(false),error=ref(''),notice=ref('')
const filters=ref({search:'',course_id:'',section_id:'',academic_year_id:'',semester_id:'',classification:'',status:'',sort:'newest'})
let epoch=0
async function load(){const v=++epoch;busy.value=true;error.value='';try{const [o,s]=await Promise.all([apiClient.get('/enrollment/academic/options'),apiClient.get('/enrollment/academic/sections',{params:{page:sectionPage.value,course_id:filters.value.course_id,academic_year_id:filters.value.academic_year_id,semester_id:filters.value.semester_id}})]);if(v!==epoch)return;options.value=o.data.data;sections.value=s.data.data;profPage.value=1;if(mode.value==='scheduling'){if(sectionId.value)await loadSchedules();else data.value=null}else{const r=await apiClient.get(`/enrollment/academic/${mode.value}`,{params:{...filters.value,page:page.value}});if(v===epoch)data.value=r.data.data}}catch(e){if(v===epoch)error.value=safeError(e)}finally{if(v===epoch)busy.value=false}}
async function loadSchedules(){if(!sectionId.value)return;const v=++epoch;busy.value=true;error.value='';try{const r=await apiClient.get('/enrollment/academic/schedules',{params:{section_id:sectionId.value,search:filters.value.search,page:page.value}});if(v===epoch)scheduleData.value=r.data.data}catch(e){if(v===epoch)error.value=safeError(e)}finally{if(v===epoch)busy.value=false}}
async function moreSections(delta){sectionPage.value+=delta;const v=epoch;try{const r=await apiClient.get('/enrollment/academic/sections',{params:{page:sectionPage.value,course_id:filters.value.course_id,academic_year_id:filters.value.academic_year_id,semester_id:filters.value.semester_id}});if(v===epoch)sections.value=r.data.data}catch(e){if(v===epoch)error.value=safeError(e)}}
async function moreProfessors(){const v=epoch;try{const r=await apiClient.get('/enrollment/academic/options',{params:{page:++profPage.value}});if(v===epoch){options.value.professors.data.push(...r.data.data.professors.data);options.value.professors.current_page=r.data.data.professors.current_page}}catch(e){if(v===epoch)error.value=safeError(e)}}
function editSection(s){form.value=s?{...s}:{course_id:'',academic_year_id:'',semester_id:'',section_name:'',year_level:1,capacity:40,status:'open',adviser_id:null}}
function editSchedule(s,copy=false){form.value=s?{...s,id:copy?null:s.id,original_professor_id:copy?null:s.professor_id,start_time:s.start_time.slice(0,5),end_time:s.end_time.slice(0,5)}:{section_id:Number(sectionId.value),subject_id:'',professor_id:'',day:'Monday',start_time:'',end_time:'',room:''}}
async function save(confirmed=false){if(busy.value)return;const v=++epoch;busy.value=true;error.value='';try{const path=`/enrollment/academic/${mode.value==='sections'?'sections':'schedules'}`;const payload={...form.value},originalProfessor=payload.original_professor_id;delete payload.original_professor_id;for(const key of ['course_id','academic_year_id','semester_id','year_level','capacity','section_id','subject_id','professor_id','adviser_id'])if(payload[key]!==undefined)payload[key]=payload[key]?Number(payload[key]):null;if(!confirmed&&payload.id&&originalProfessor&&Number(originalProfessor)!==payload.professor_id){reassignment.value=payload;return}if(payload.id)await apiClient.put(`${path}/${payload.id}`,payload);else await apiClient.post(path,payload);if(v!==epoch)return;form.value=null;reassignment.value=null;notice.value='Saved successfully.';await load()}catch(e){if(v===epoch)error.value=safeError(e)}finally{if(v===epoch)busy.value=false}}
async function confirmReassignment(){form.value={...reassignment.value};await save(true)}
const professorName=id=>{const p=options.value?.professors?.data?.find(row=>Number(row.id)===Number(id));return p?`${p.user?.profile?.first_name||''} ${p.user?.profile?.last_name||''}`.trim()||p.employee_number:'the selected Professor'}
async function deleteSchedule(){if(busy.value)return;const v=++epoch;busy.value=true;error.value='';try{await apiClient.delete(`/enrollment/academic/schedules/${remove.value.id}`,{data:{version:remove.value.version,confirmed:true}});if(v!==epoch)return;remove.value=null;notice.value='Schedule removed.';await loadSchedules()}catch(e){if(v===epoch)error.value=safeError(e);remove.value=null}finally{if(v===epoch)busy.value=false}}
async function inspect(id){const v=++epoch;busy.value=true;error.value='';try{const r=await apiClient.get(`/enrollment/academic/records/${id}`);if(v===epoch)record.value=r.data.data}catch(e){if(v===epoch)error.value=safeError(e)}finally{if(v===epoch)busy.value=false}}
watch(()=>route.name,()=>{data.value=null;scheduleData.value=null;sectionId.value='';form.value=null;record.value=null;remove.value=null;reassignment.value=null;page.value=1;sectionPage.value=1;filters.value={search:'',course_id:'',section_id:'',academic_year_id:'',semester_id:'',classification:'',status:'',sort:'newest'};load()},{immediate:true});onBeforeUnmount(()=>{epoch++})
</script>
<template><header class="page-header en-no-print"><p class="page-kicker">Enrollment</p><h1 class="page-title">{{ mode==='sections'?'Sections':mode==='scheduling'?'Scheduling':'Enrollment Records' }}</h1></header><p v-if="error" role="alert">{{ error }} <button :disabled="busy" @click="load">Reload</button></p><p v-if="notice" role="status">{{ notice }}</p><p v-if="busy" role="status">Loading…</p>
<template v-if="options"><form class="en-card en-grid en-no-print" @submit.prevent="page=1;load()"><label>{{ mode==='records'?'Student name or number':mode==='sections'?'Section name':'Subject name or code' }}<input v-model="filters.search" maxlength="100"></label><label>Course<select v-model="filters.course_id"><option value="">All courses</option><option v-for="c in options.courses" :key="c.id" :value="c.id">{{ c.course_name }}</option></select></label><label>Academic year<select v-model="filters.academic_year_id"><option value="">All years</option><option v-for="y in options.academic_years" :key="y.id" :value="y.id">{{ y.school_year }}</option></select></label><label>Semester<select v-model="filters.semester_id"><option value="">All semesters</option><option v-for="s in options.semesters" :key="s.id" :value="s.id">{{ s.semester_name }}</option></select></label><template v-if="mode==='records'"><label>Classification<select v-model="filters.classification"><option value="">All classifications</option><option v-for="c in ['regular','irregular','transferee','returnee']" :key="c" :value="c">{{ label(c) }}</option></select></label><label>Section<select v-model="filters.section_id"><option value="">All sections</option><option v-for="s in sections.data" :key="s.id" :value="s.id">{{ s.section_name }}</option></select></label><label>Sort<select v-model="filters.sort"><option v-for="s in ['newest','oldest','student_number','name','classification']" :key="s" :value="s">{{ label(s) }}</option></select></label></template><label v-if="mode!=='scheduling'">Status<select v-model="filters.status"><option value="">All statuses</option><option v-for="s in mode==='sections'?['open','closed']:['pending','enrolled','completed','cancelled']" :key="s" :value="s">{{ label(s) }}</option></select></label><button :disabled="busy" type="submit">Apply filters</button></form>
<div v-if="mode==='sections'" class="en-actions en-no-print"><button :disabled="busy" @click="editSection(null)">Create section</button></div>
<template v-if="mode==='scheduling'"><div class="en-card en-no-print"><label>Section<select v-model="sectionId" :disabled="busy" @change="page=1;form=null;loadSchedules()"><option value="">Choose section</option><option v-for="s in sections.data" :key="s.id" :value="s.id">{{ s.section_name }} · {{ termLabel(s) }}</option></select></label><div v-if="sections.last_page>1" class="en-actions"><button :disabled="busy||sectionPage<=1" @click="moreSections(-1)">Previous sections</button><button :disabled="busy||sectionPage>=sections.last_page" @click="moreSections(1)">More sections</button></div><button v-if="sectionId" :disabled="busy" @click="editSchedule(null)">Add schedule</button><p v-if="sectionId && scheduleData && !scheduleData.subjects.length" role="status">No active curriculum subjects are configured for this section’s Course, year level and semester. Configure the approved curriculum before adding schedules.</p></div></template>
<form v-if="form" class="en-card en-no-print" @submit.prevent="save()"><h2>{{ form.id?'Edit':'Create' }} {{ mode==='sections'?'section':'schedule' }}</h2><div class="en-grid"><template v-if="mode==='sections'"><label>Section name<input v-model="form.section_name" required maxlength="20"></label><label>Course<select v-model="form.course_id" required><option value="">Choose Course</option><option v-for="c in options.courses" :key="c.id" :value="c.id">{{ c.course_name }}</option></select></label><label>Academic year<select v-model="form.academic_year_id" :disabled="!!form.id" required><option value="">Choose year</option><option v-for="y in options.academic_years" :key="y.id" :value="y.id">{{ y.school_year }}</option></select></label><label>Semester<select v-model="form.semester_id" :disabled="!!form.id" required><option value="">Choose semester</option><option v-for="s in options.semesters" :key="s.id" :value="s.id">{{ s.semester_name }}</option></select></label><label>Year level<input type="number" min="1" max="20" v-model.number="form.year_level" required></label><label>Capacity<input type="number" min="1" max="65535" v-model.number="form.capacity" required></label><label>State<select v-model="form.status"><option value="open">Open</option><option value="closed">Closed</option></select></label><label>Adviser<select v-model="form.adviser_id"><option :value="null">No adviser</option><option v-for="p in options.professors.data" :key="p.id" :value="p.id">{{ p.user?.profile?.first_name }} {{ p.user?.profile?.last_name }} · {{ p.employee_number }}</option></select></label></template>
<template v-else><label>Section / copy destination<select v-model="form.section_id" :disabled="!!form.id" required><option v-for="s in sections.data" :key="s.id" :value="s.id">{{ s.section_name }}</option></select></label><label>Subject<select v-model="form.subject_id" required><option value="">Choose subject</option><option v-for="s in scheduleData?.subjects" :key="s.id" :value="s.id">{{ s.subject_code }} — {{ s.subject_name }}</option></select></label><label>Professor<select v-model="form.professor_id" required><option value="">Choose Professor</option><option v-for="p in options.professors.data" :key="p.id" :value="p.id">{{ p.user?.profile?.first_name }} {{ p.user?.profile?.last_name }} · {{ p.employee_number }}</option></select></label><label>Day<select v-model="form.day"><option v-for="d in scheduleData?.days" :key="d">{{ d }}</option></select></label><label>Start time<input type="time" v-model="form.start_time" required></label><label>End time<input type="time" v-model="form.end_time" required></label><label>Room<input v-model="form.room" required maxlength="50"></label></template></div><button v-if="options.professors.current_page<options.professors.last_page" type="button" :disabled="busy" @click="moreProfessors">More Professors</button><div class="en-actions"><button :disabled="busy" type="submit">Save {{ mode==='sections'?'section':'schedule' }}</button><button class="en-secondary" :disabled="busy" type="button" @click="form=null">Cancel</button></div></form>
<template v-if="mode==='scheduling' && scheduleData"><h2>{{ scheduleData.section.section_name }} · {{ termLabel(scheduleData.section) }}</h2><EnrollmentSchedule :schedules="scheduleData.schedules.data"><template #actions="{schedule}"><div class="en-actions en-no-print"><button :disabled="busy" @click="editSchedule(schedule)">Edit</button><button :disabled="busy" @click="editSchedule(schedule,true)">Copy</button><button :disabled="busy" @click="remove=schedule">Delete</button></div></template></EnrollmentSchedule><div v-if="scheduleData.schedules.last_page>1" class="en-actions en-no-print"><button :disabled="busy||page<=1" @click="page--;loadSchedules()">Previous schedules</button><button :disabled="busy||page>=scheduleData.schedules.last_page" @click="page++;loadSchedules()">More schedules</button></div></template>
<div v-if="data && mode!=='scheduling'" class="en-card en-table en-no-print"><table><thead><tr v-if="mode==='sections'"><th>Section / term</th><th>Course / year</th><th>Enrolled / reserved / capacity</th><th>State</th><th>Action</th></tr><tr v-else><th>Student</th><th>Course / section / term</th><th>Classification</th><th>Status</th><th>Action</th></tr></thead><tbody><template v-for="r in data.data" :key="r.id"><tr v-if="mode==='sections'"><td>{{ r.section_name }}<br>{{ termLabel(r) }}</td><td>{{ r.course?.course_name }} · {{ r.year_level }}</td><td>{{ r.enrolled_count }} / {{ r.reserved_count }} / {{ r.capacity }}</td><td><span class="en-badge">{{ label(r.status) }}</span></td><td><button :disabled="busy" @click="editSection(r)">Edit section</button></td></tr><tr v-else><td>{{ r.student?.student_number }}<br>{{ r.student?.user_profile?.first_name }} {{ r.student?.user_profile?.last_name }}</td><td>{{ r.section?.course?.course_name || r.student?.course?.course_name }}<br>{{ r.section?.section_name }} · {{ termLabel(r) }}</td><td><span class="en-badge">{{ r.application?label(r.application.classification):'Legacy record' }}</span></td><td><span class="en-badge">{{ label(r.status) }}</span></td><td><button v-if="['enrolled','completed'].includes(r.status)" :disabled="busy" @click="inspect(r.id)">View COR</button></td></tr></template><tr v-if="!data.data.length"><td colspan="5">No records found.</td></tr></tbody></table><div class="en-actions"><button :disabled="busy||page<=1" @click="page--;load()">Previous</button><span>Page {{ page }} of {{ data.last_page }}</span><button :disabled="busy||page>=data.last_page" @click="page++;load()">Next</button></div></div></template>
<EnrollmentDialog v-if="record" labelledby="en-record-detail" :busy="busy" wide @cancel="record=null"><header class="en-dialog-header en-no-print"><div><h2 id="en-record-detail">{{ record.name }}</h2><p>{{ record.student_number }} · {{ record.course }}</p></div><button type="button" :disabled="busy" aria-label="Close enrollment record" @click="record=null">Close</button></header><div class="en-dialog-body"><EnrollmentCor :record="record"/></div></EnrollmentDialog>
<EnrollmentDialog v-if="remove" labelledby="en-delete-schedule" :busy="busy" @cancel="remove=null"><h2 id="en-delete-schedule">Delete this schedule?</h2><p>{{ remove.subject?.subject_code }} · {{ remove.day }} · {{ remove.start_time }}–{{ remove.end_time }}</p><p>Schedules used by academic enrollment cannot be deleted.</p><div class="en-actions"><button @click="remove=null">Go back</button><button :disabled="busy" @click="deleteSchedule">Confirm deletion</button></div></EnrollmentDialog>
<EnrollmentDialog v-if="reassignment" labelledby="en-reassign-professor" :busy="busy" @cancel="reassignment=null"><h2 id="en-reassign-professor">Reassign this teaching assignment?</h2><p>{{ scheduleData?.subjects?.find(s=>s.id===reassignment.subject_id)?.subject_code }} in {{ scheduleData?.section?.section_name }} will be assigned to {{ professorName(reassignment.professor_id) }}.</p><p>The previous Professor will immediately lose access to this class. Submitted, approved, or published grade sheets cannot be reassigned.</p><div class="en-actions"><button :disabled="busy" @click="reassignment=null">Go back</button><button :disabled="busy" @click="confirmReassignment">Confirm reassignment</button></div></EnrollmentDialog></template>
