<script setup>
import { computed, onMounted, ref } from 'vue'
import { apiClient } from '../services/apiClient'

const sections = ['Profile', 'Account', 'Student Status', 'Document Status', 'Contact Information', 'Notifications', 'Academic Preferences', 'Appearance', 'Security']
const active = ref('Profile'), open = ref(false), data = ref(null), error = ref(''), success = ref(''), loading = ref(true), saving = ref(false), saved = ref('')
const form = ref({ preferred_display_name: '', bio: '', email: '', contact_number: '', address: '', notification_preferences: {}, academic_preferences: {}, appearance: 'system', current_password: '', password: '', password_confirmation: '' })
const editable = ['Profile', 'Contact Information', 'Notifications', 'Academic Preferences', 'Appearance']
const dirty = computed(() => editable.includes(active.value) && saved.value !== JSON.stringify(form.value))
const status = computed(() => data.value?.student_status || {})
const messageFor = (err, fallback) => {
  const fields = err.response?.data?.errors
  return fields ? Object.values(fields).flat().join(' ') : (err.response?.data?.message || fallback)
}
const applyAppearance = () => { document.documentElement.dataset.studentTheme = form.value.appearance; localStorage.setItem('cdm-student-appearance', form.value.appearance) }
const load = async () => { loading.value = true; error.value = ''; try { data.value = (await apiClient.get('/student/settings')).data.data; Object.assign(form.value, { preferred_display_name: data.value.profile.preferred_display_name || '', bio: data.value.profile.bio || '', email: data.value.contact.personal_email || '', contact_number: data.value.contact.mobile || '', address: data.value.contact.address || '', notification_preferences: data.value.preferences.notification_preferences || {}, academic_preferences: data.value.preferences.academic_preferences || {}, appearance: data.value.appearance || 'system' }); saved.value = JSON.stringify(form.value); applyAppearance() } catch (err) { error.value = err.response?.data?.message || 'Unable to load settings.' } finally { loading.value = false } }
const reset = () => { Object.assign(form.value, JSON.parse(saved.value)); applyAppearance(); error.value = '' }
const save = async (path, payload, message) => { saving.value = true; error.value = ''; try { data.value = (await apiClient.patch(path, payload)).data.data; saved.value = JSON.stringify(form.value); success.value = message } catch (err) { error.value = messageFor(err, 'Unable to save settings.') } finally { saving.value = false } }
const saveProfile = () => save('/student/settings/profile', { preferred_display_name: form.value.preferred_display_name, bio: form.value.bio }, 'Profile saved.')
const saveContact = () => save('/student/settings/contact', { email: form.value.email, contact_number: form.value.contact_number, address: form.value.address }, 'Contact information saved.')
const savePreferences = () => { applyAppearance(); return save('/student/settings/preferences', { notification_preferences: form.value.notification_preferences, academic_preferences: form.value.academic_preferences, appearance: form.value.appearance }, 'Preferences saved.') }
const saveActive = () => ({ Profile: saveProfile, 'Contact Information': saveContact, Notifications: savePreferences, 'Academic Preferences': savePreferences, Appearance: savePreferences }[active.value]?.())
const changePassword = async () => { saving.value = true; try { await apiClient.post('/change-password', { current_password: form.value.current_password, password: form.value.password, password_confirmation: form.value.password_confirmation }); success.value = 'Password changed.'; form.value.current_password = form.value.password = form.value.password_confirmation = '' } catch (err) { error.value = messageFor(err, 'Unable to change password.') } finally { saving.value = false } }
const upload = async (event) => { const file = event.target.files?.[0]; if (!file) return; const payload = new FormData(); payload.append('avatar', file); saving.value = true; try { data.value = (await apiClient.post('/student/settings/avatar', payload, { headers: { 'Content-Type': 'multipart/form-data' } })).data.data; success.value = 'Profile picture updated.' } catch (err) { error.value = messageFor(err, 'Avatar upload failed.') } finally { saving.value = false } }
const removeAvatar = async () => { await apiClient.delete('/student/settings/avatar'); await load(); success.value = 'Profile picture removed.' }
onMounted(load)
</script>

<template>
  <main class="settings"><header><button class="menu" type="button" @click="open = true">Settings menu</button><div><p>Student Settings</p><h1>Your account and preferences</h1></div></header>
    <div class="layout"><aside :class="{ open }"><strong>Settings</strong><button v-for="section in sections" :key="section" :class="{ active: active === section }" @click="active = section; open = false">{{ section }}</button></aside><div v-if="open" class="backdrop" @click="open = false" />
      <section class="content"><p v-if="loading">Loading settings...</p><p v-else-if="error" class="error" role="alert">{{ error }}</p><article v-else><p v-if="success" class="toast" role="status">{{ success }}</p><div v-if="dirty" class="save-bar" role="status"><span>You have unsaved changes</span><div><button type="button" :disabled="saving" @click="reset">Reset</button><button type="button" :disabled="saving" @click="saveActive">{{ saving ? 'Saving...' : 'Save Changes' }}</button></div></div><h2>{{ active }}</h2>
        <template v-if="active === 'Profile'"><img v-if="data.profile.avatar_url" class="avatar" :src="data.profile.avatar_url" alt="Profile picture" /><label>Profile picture<input type="file" accept="image/png,image/jpeg,image/webp" :disabled="saving" @change="upload" /></label><button v-if="data.profile.avatar_url" :disabled="saving" @click="removeAvatar">Remove picture</button><label>Preferred display name<input v-model="form.preferred_display_name" /></label><label>Bio<textarea v-model="form.bio" /></label></template>
        <template v-else-if="active === 'Contact Information'"><label>Personal email<input v-model="form.email" type="email" /></label><label>Mobile<input v-model="form.contact_number" /></label><label>Address<textarea v-model="form.address" /></label></template>
        <template v-else-if="active === 'Notifications' || active === 'Academic Preferences'"><label v-for="key in active === 'Notifications' ? ['document_updates','appointment_reminders','academic_warnings','adviser_alerts','email','in_app'] : ['warning_notifications','study_plan_reminders','adviser_alerts','ai_suggestions']" :key="key" class="toggle"><input v-model="(active === 'Notifications' ? form.notification_preferences : form.academic_preferences)[key]" type="checkbox" /> {{ key.replaceAll('_', ' ') }}</label></template>
        <template v-else-if="active === 'Appearance'"><label v-for="option in ['light','dark','system']" :key="option" class="tile"><input v-model="form.appearance" type="radio" :value="option" @change="applyAppearance" /> {{ option }}</label></template>
        <template v-else-if="active === 'Document Status'"><progress :value="data.document_status.complete" :max="data.document_status.total || 1" /><p>{{ data.document_status.complete }} of {{ data.document_status.total }} documents verified</p><ul><li v-for="item in data.document_status.items" :key="item.name">{{ item.name }}: {{ item.status }}</li></ul><RouterLink to="/student-management">View documents</RouterLink></template>
        <template v-else-if="active === 'Security'"><label>Current password<input v-model="form.current_password" type="password" /></label><label>New password<input v-model="form.password" type="password" /></label><label>Confirm password<input v-model="form.password_confirmation" type="password" /></label><button :disabled="saving" @click="changePassword">{{ saving ? 'Saving...' : 'Change password' }}</button></template>
        <dl v-else><template v-for="(value, key) in active === 'Account' ? data.account : status" :key="key"><dt>{{ key.replaceAll('_', ' ') }}</dt><dd>{{ value || 'Not available' }}</dd></template></dl>
      </article></section>
    </div>
  </main>
</template>

<style scoped>
.settings{max-width:1180px;margin:auto;padding:24px}.settings>header{display:flex;gap:12px;align-items:center}.settings header p{margin:0;color:#28734b;font-weight:700}.settings h1{margin:4px 0}.layout{display:grid;grid-template-columns:220px 1fr;gap:18px;margin-top:18px}aside,article{background:#fffdf8;border:1px solid #dce7df;border-radius:14px;box-shadow:0 5px 18px #123a1a0d}aside{display:grid;align-content:start;padding:12px}aside button{border:0;background:transparent;text-align:left;padding:10px;border-radius:8px;transition:background 180ms ease}aside button.active,aside button:hover{background:#e6f3e9;color:#155f39;font-weight:800}article{display:grid;gap:13px;padding:22px}article h2{margin:0}label{display:grid;gap:6px;font-weight:700}input,textarea{border:1px solid #cddbd0;border-radius:8px;padding:10px}input:focus,textarea:focus,button:focus-visible{outline:3px solid #9dcea9;outline-offset:2px}textarea{min-height:90px}.toggle,.tile{padding:10px;border:1px solid #dce7df;border-radius:9px}.tile{display:flex;gap:8px;text-transform:capitalize}.toast{padding:10px;border-radius:8px;background:#edf7ef;color:#155f39}.save-bar{position:sticky;bottom:12px;z-index:2;display:flex;justify-content:space-between;gap:12px;align-items:center;padding:12px 14px;border-radius:12px;background:#f3faf4;border:1px solid #b9d9c0;box-shadow:0 8px 22px #123a1a1a;transition:transform 180ms ease,opacity 180ms ease}.save-bar div{display:flex;gap:8px}.save-bar button,article>button,.menu{border:0;border-radius:7px;background:#176c42;color:#fff;padding:10px 14px;font-weight:800}.save-bar button:first-child{background:#fff;color:#176c42;border:1px solid #176c42}.avatar{width:72px;height:72px;border-radius:50%;object-fit:cover}.menu{display:none}.error{color:#a8291f}dt{text-transform:capitalize;color:#5e7064;margin-top:10px}dd{margin:3px 0;font-weight:700}@media(max-width:720px){.layout{display:block}.menu{display:block}aside{position:fixed;inset:0 auto 0 0;width:min(290px,82vw);z-index:50;transform:translateX(-105%);transition:transform 180ms ease}aside.open{transform:translateX(0)}.backdrop{position:fixed;inset:0;background:#10261a66;z-index:40}.save-bar{align-items:stretch;flex-direction:column}.save-bar div{display:grid;grid-template-columns:1fr 1fr}}@media(prefers-reduced-motion:reduce){*,*:before,*:after{transition:none!important}}
</style>
<style scoped>
:global(html[data-student-theme='dark']) .settings{background:#17221b;color:#edf6ef}:global(html[data-student-theme='dark']) .settings aside,:global(html[data-student-theme='dark']) .settings article{background:#213127;border-color:#3d5645;box-shadow:0 5px 18px #0004}:global(html[data-student-theme='dark']) .settings input,:global(html[data-student-theme='dark']) .settings textarea{background:#17221b;color:#edf6ef;border-color:#587061}:global(html[data-student-theme='dark']) .settings dt{color:#b9cabc}:global(html[data-student-theme='dark']) .settings .save-bar{background:#1e3728;border-color:#4c805c}:global(html[data-student-theme='light']) .settings{background:#f7faf7;color:#213329}.settings{max-width:850px;border-radius:16px}.toggle{display:flex;align-items:center;justify-content:space-between;min-height:44px;padding:8px 10px;text-transform:capitalize}.toggle input{appearance:none;width:44px;height:24px;margin:0;padding:0;border-radius:999px;background:#bdc9c0;border:0;cursor:pointer;position:relative;transition:background 180ms ease}.toggle input::after{content:'';position:absolute;top:3px;left:3px;width:18px;height:18px;border-radius:50%;background:#fff;box-shadow:0 1px 3px #0004;transition:transform 180ms ease}.toggle input:checked{background:#176c42}.toggle input:checked::after{transform:translateX(20px)}.tile input{width:auto;padding:0}.avatar{width:88px;height:88px}.settings label input[type='file']{max-width:260px;padding:7px}.settings article>button{align-self:start;padding:7px 10px;font-size:.85rem}@media(max-width:720px){.settings{padding:16px}.settings article{padding:16px}.toggle{min-height:42px}}@media(prefers-reduced-motion:reduce){.toggle input,.toggle input::after{transition:none}}
</style>
